version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    mysql:

        image: mysql:5.7.27
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./store_files:/store_files_mysql/
            - ./mysql.cnf:/etc/mysql/mysql.cnf

    webserver:
        image: puckel/docker-airflow:1.10.4
        restart: always
        depends_on:
            - postgres
            - mysql
        environment:
            - INSTALL_MYSQL=y
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
            - AIRFLOW__SMTP__SMTP_USER=shivanshsinghchauhan@gmail.com
            - AIRFLOW__SMTP__SMTP_PASSWORD=kfyfbmzlrdktaiwi
            - AIRFLOW__SMTP__SMTP_PORT=587
            - AIRFLOW__SMTP__SMTP_MAIL_FROM=Airflow
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./conf/airflow.cfg:/usr/local/airflow/airflow.cfg
            - ./store_files:/usr/local/airflow/store_files_airflow
            #- ./logs:/usr/local/airflow/logs
            #- ./json_logs:/var/lib/docker/containers 
            #- ./airflow:/usr/local/airflow
            #- ./config:/usr/local/airflow/config
            #- /Users/apple/opt/anaconda3/lib/python3.7/site-packages/airflow/config/jsonformatter.py:/usr/local/lib/python3.7/site-packages/airflow/config/jsonformatter.py
            #- /Users/apple/opt/anaconda3/lib/python3.7/site-packages/airflow/config/log_config.py:/usr/local/lib/python3.7/site-packages/airflow/config/log_config.py
            #- /Users/apple/opt/anaconda3/lib/python3.7/site-packages/airflow/config/__init__.py:/usr/local/lib/python3.7/site-packages/airflow/config/__init__.py
            #- /Users/apple/opt/anaconda3/lib/python3.7/site-packages/airflow/logging_config.py:/usr/local/lib/python3.7/site-packages/airflow/logging_config.py
            #- /Users/apple/opt/anaconda3/lib/python3.7/site-packages/airflow/config:/usr/local/lib/python3.7/site-packages/airflow/config
            #- ./log_format:/usr/local/airflow/log_format
            #- /Users/apple/opt/anaconda3/lib/python3.7/site-packages/airflow/logging_config.py:/usr/local/airflow/log_format/logging_config.py
            #- ./airflow.cfg:/usr/local/airflow/airflow.cfg # changed the color 
            #- ./store_sales_project2:/usr/local/airflow/airflow.cfg
            #- ./store_files:/Users/apple/Desktop/airflow/store_sales_project2/dags 
            - ./sql_files:/usr/local/airflow/sql_files
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
